Added Microsoft Standard SKU to the CDN Fluent Definition
Azure/azure-libraries-for-net pull request #1163
Opened 2020-11-06 22:26 UTC by MatiasT

I added the required implementation to fix the bug 1162 reported [here](https://github.com/Azure/azure-libraries-for-net/issues/1162). Please review and confirm it works as expected.

2020-11-07 17:33 UTC, Renkon requested changes

2020-11-07 17:33 UTC, Renkon commented on src/ResourceManagement/Cdn/Domain/CdnProfile/Definition/IDefinition.cs
> +        /// Selects the Standard Akamai SKU.
Selects the Standard Microsoft SKU

2020-11-07 17:33 UTC, Renkon commented on src/ResourceManagement/Cdn/Domain/InterfaceImpl/CdnProfileImpl.cs
> +        /// Selects the Standard Akamai SKU.
Selects the Standard Microsoft SKU

2020-11-08 02:44 UTC, Renkon approved these changes

2020-11-09 01:49 UTC, weidongxu-microsoft approved these changes

2020-11-09 02:40 UTC, xccc-msft approved these changes

2020-11-09 02:48 UTC, ChenTanyi approved these changes

2020-11-25 06:47 UTC, merged